# name: "sample-workflow"

# on:
#   issue_comment:
#     types: [created]

# permissions:
#   pull-requests: write
#   deployments: write
#   contents: write
#   checks: read
#   statuses: read

# jobs:
#   sample:
#     if: ${{ github.event.issue.pull_request }} # only run on pull request comments
#     environment: production-secrets
#     runs-on: ubuntu-latest
#     steps:
#       # Need to checkout for testing the Action in this repo
#       - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # pin@v7.0.0
#         with:
#           persist-credentials: false

#       # Start the branch deployment
#       - uses: ./
#         id: branch-deploy
#         with:
#           admins: octocat

#       # Check out the ref from the output of the IssueOps command
#       - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # pin@v7.0.0
#         if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
#         with:
#           ref: ${{ steps.branch-deploy.outputs.sha }}
#           persist-credentials: false

#       # Do some fake "noop" deployment logic here
#       - name: fake noop deploy
#         if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
#         run: echo "I am doing a fake noop deploy"

#       # Do some fake "regular" deployment logic here
#       - name: fake regular deploy
#         if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
#         run: echo "I am doing a fake regular deploy"
