name: Update Latest Release Tag
run-name: Update ${{ github.event.inputs.major_version_tag }} with ${{ github.event.inputs.source_tag }}

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'The tag or reference to use as the source (example: v8.0.0)'
        required: true
        default: vX.X.X
      major_version_tag:
        description: 'The major release tag to update with the source (example: v8)'
        required: true
        default: vX

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: tag new target
        env:
          SOURCE_TAG: ${{ github.event.inputs.source_tag }}
          MAJOR_VERSION_TAG: ${{ github.event.inputs.major_version_tag }}
        run: git tag -f ${MAJOR_VERSION_TAG} ${SOURCE_TAG}

      - name: push new tag
        env:
          MAJOR_VERSION_TAG: ${{ github.event.inputs.major_version_tag }}
        run: git push origin ${MAJOR_VERSION_TAG} --force
